### ISSUE TITLE
add graphql-tag/loader as hook for nodejs | feature

### ISSUE THREAD

**Issue by seeden** [apollostack/graphql-tag#15]
It would be nice to have graphql-tag/loader available in the nodejs as hook.
That means I can use 

``` js
import query from './queries/query.graphql';
```

in the nodejs as well.
It is very easy to do that with https://www.npmjs.com/package/require-hacker

**Comment by stubailo** [comment]
I think require hooks are no longer recommended as a best practice for Node, right? The correct approach is to have a build step that outputs `.js` files I think.

**Comment by seeden** [comment]
It is much easier to work with hooks when you have isomorphic application. How you are using it in your isomorphic application?

**Comment by stubailo** [comment]
I don't use the webpack loader personally, I'm using the template literal and putting the queries inside the JS. I think it could be cool to add a require hook to this package, I'm just saying the best way is to run a build step on the server code.

**Comment by abhiaiyer91** [comment]
Agreed best to let developer tools handle understanding .graphql
