### ISSUE TITLE
Typescript error: Cannot find module 'query.gql'

### ISSUE THREAD

**Issue by val-samonte** [apollostack/graphql-tag#42]
I am using typescript 2.1.4 and using graphql-tag/loader for webpack. Unfortunately I am receiving this error whenever I compile from typescript.

**Comment by val-samonte** [comment]
Sorry, been able to find a solution by using "require" instead of "import", eg:
const query = require('gql/Query.gql');

Closing this issue.

**Comment by stubailo** [comment]
BTW look into typescript code generation with apollo-codegen: https://github.com/apollographql/apollo-codegen

**Comment by veeramarni** [comment]
Seems like `import` not working after latest update.

**Comment by viridia** [comment]
I'm having the same problem by the way; I'm using graphql-loader to load .graphql files, but I have to use require() instead of import in typescript source code.

**Comment by yordis** [comment]
The correct fix to this is to extend the Typescript definition, as such.

```
declare module "*.qql" {
  const content: any;
  export default content;
}

declare module "*.graphql" {
  const content: any;
  export default content;
}
```

The reason I use `any` value is because the function `qql` from the package returns `any` https://github.com/apollographql/graphql-tag/blob/1fd2c9d0378163d76b8091dd2dbd3afc6142a34a/index.d.ts#L1

**Comment by dfee** [comment]
@yordis this doesn't seem to work for me. My understanding is that a `*.d.ts` file can be anywhere in my package -- so long as i don't explicitly declare `files` in my `.tsconfig.json`.

I'm still getting this error, though, despite a directory that looks like this:
```
/pkg
  /queries
    webpack.d.ts
    query1.gql
    query2.gql
```

**Comment by dfee** [comment]
### ❗️SOLVED❗️
Oh my god, I found the problem. @yordis's comment was almost right.

Here's the problem with his code (first three lines):
```ts
// webpack.d.ts
declare module "*.qql" {
  const content: any;
```

You're probably not seeing what's wrong here, so I'll make it explicit with capital letters:
```ts
declare module "*.QQL" {
```

This was either a grave typo, or in some world people name graphql files with the extension QQL.

Here's the working snippet:
```ts
// webpack.d.ts
declare module "*.qql" {
  const content: any;
  export default content;
}

declare module "*.graphql" {
  const content: any;
  export default content;
}
```

@yordis if you can update your comment, please do.

**Comment by yordis** [comment]
@dfee English 😢 

I update the message and also improve the typespec.

**Comment by dfee** [comment]
I ended up using `custom.d.ts` as described here: https://webpack.js.org/guides/typescript/#importing-other-assets

I think this issue can be safely closed.

**Comment by EloB** [comment]
Anyone know how to add:
```ts
declare module "*.graphql" {
  const content: string;
  export default content;
}
```

Into a package inside a monorepo using like Turborepo, Lerna or Nx? That could be shared? Like the scoped packages from @types?

I know I can create a package called `@types/custom-app` but I'm wondering if it's possible to add without that name?

**Comment by yordis** [comment]
@EloB check this,

So a reusable package: https://github.com/straw-hat-team/types/blob/master/src/css-modules.ts

Then import it inside a `.d.ts` file that will be loaded.

For example, `<root>/src/@tpes/index.d.ts`

```ts
/// <reference types="@straw-hat/types/dist/css-modules" />
/// <reference types="@straw-hat/types/dist/svgr-webpack" />
```
