### ISSUE TITLE
const keyword causing errors with IE <= 10

### ISSUE THREAD

**Issue by rakis** [apollostack/graphql-tag#7]
The parseDocument function uses the const keyword, which causes issues with browsers that don't currently support it, e.g. IE <= 10.

I can get around it by using babel-loader for the graphql-tag package, but I want to say the ideal would be to resolve this at the package level.

```javascript
function parseDocument(doc) {
  if (cache[doc]) {
    return cache[doc];
  }

  const parsed = parse(doc);

  if (!parsed || parsed.kind !== 'Document') {
    throw new Error('Not a valid GraphQL document.');
  }

  cache[doc] = parsed;

  return parsed;
}
```

**Comment by stubailo** [comment]
Oh darn! My goal was to avoid stuff like this. Would you want to submit a pr for this? I can also easily fix it myself but it's an easy opportunity for a quick contribution :)

**Comment by stubailo** [comment]
Just published a new version with the fix! Let me know if it doesn't work.
